cam_info:
  -
    cam_id: 1
    cam_serial_num: "203522250888"
    type: realsense
  -
    cam_id: 2
    cam_serial_num: "944122074119"
    type: realsense


cam_config:
  realsense:
    width: 640
    height: 480
    fps: 30
    processing_preset: 1
    depth: True

